work_dir: &work_dir logs/{exp_name}
deterministic: False

data_dir: {AGD20K_dir}
GT_data_dir: {sampled Contextual-AGD20K_dir} ## ex) ../../06_Affordance-R1/Affordance-R1/vis_results_refine_anno_v2/sampled/AGD20K_refine/ 

load:
  encoder_ckpt: ./ViT-B-16.pt
  all_ckpt: # leave blank for training

batch_size: 32 # real batch size = batch_size * accum_itersss
img_size: 224
split_type: Seen
num_exo: 0
PL_mode: refined
aug4imgRatio: 0.5

optimizer:
  lr: 0.0001
  lr_encoder_coeff: 0.1
  betas:
    - 0.9
    - 0.95
  wd: 0.01

  max_iter: 5000000
  lr_step:  20 ## 5000000
  lr_gamma: 0.5 ##
  num_epochs: 40
  accum_iter: 2
  sche_type: step

model:
  encoder_type: CLIP
  encoder_params:
    width: 768
    layers: 12
    heads: 12
    output_dim: 512
  decoder_embed_dim: 512

  pred_model_type: SAM
  pred_decoder_args:
    mlp_dim: 2048
    depth: 2
    use_up: 2
    use_additional_token: True
    conv_first: True

  margin: 0.1

loss:
  kl_loss_coeff: 1.0
  sim_loss_coeff: 10.
  exo_cls_coeff: 10.
  noun_sim_coeff: 1.
  part_sim_coeff: 0.1
  context_sim_coeff: 0.01 ## 
